name: wordpress-docker-sync

services:
 your-name:
   image: wordpress:latest
   container_name: your-name
   volumes:
     - ./wordpress:/var/www/html
     - ./change-url.sh:/usr/local/bin/change-url.sh
     - ./.env.your-name:/usr/local/bin/.env
   environment:
     - WORDPRESS_DB_NAME
     - WORDPRESS_TABLE_PREFIX
     - WORDPRESS_DB_HOST
     - WORDPRESS_DB_USER
     - WORDPRESS_DB_PASSWORD
     - WORDPRESS_DEBUG=1
     - DOCKER_PORT
   restart: always
   ports:
     - "${DOCKER_PORT}:80"
   entrypoint: ["/bin/bash", "-c", "/usr/local/bin/change-url.sh"]